[package]
name = "rape-by-proxy"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
craftls = "0.0.2"
rustls-pki-types = "1"
webpki-roots = "1"
#craftls = { path = "../rustls", features = [ "logging" ]}

[dev-dependencies]
